blueprint:
  name: View Assist - Get Sports Scores
  description:
    Get sports scores for your favorite teams (View Assist getsportsscores
    v 1.4.1)
  domain: automation
  input:
    language:
      name: Language
      description: The desired spoken language
      default: en
      selector:
        language:
          languages:
            - de
            - en
            - es
            - fr
            - it
          no_sort: false
          native_name: false
    trigger_phrases:
      name: Trigger Phrases
      description: The phrases to trigger the sports score conversation
      default:
        - how did [the] {team} do
        - (what is | what's) the score of the {team} (game | match)
        - how (is | are) [the] {team} doing
        - how (is | are) [the] {team} (game | match) [going]
      selector:
        object: {}
    team_tracker:
      name: Team Tracker Sensor
      description: The Team Tracker sesnor entity that holds data (example sensor.team_tracker)
      default: sensor.zui_test000
      selector:
        entity:
          filter:
            - integration: teamtracker
          multiple: false
    college_teams:
      name: College Teams
      description:
        College Teams can be added but it is complicated.  You will need
        to know a few specifics for defining.  See Team Tracker docs here.
      default:
        college_teams:
          lsu:
            team_id: LSU
            conference_id: "8"
            league_path: college-football
            sport_path: football
      selector:
        object: {}
    view:
      name: Dashboard Sports view
      description:
        The View Assist dashboard view to use for sports scores (example
        /view-assist/sports)
      default: /view-assist/sports
trigger:
  - platform: conversation
    command: !input trigger_phrases
condition: []
action:
  - variables:
      language: !input language
      view: !input view
      team_tracker: !input team_tracker
      college_teams: !input college_teams
  - if:
      - condition: template
        value_template: "{{ true }}"
    then:
      - variables:
          query_team: "{{ college_teams['lsu']['team_id'] }}"
          sport_path: "{{ college_teams["LSU"]['sport_path'] }}"
          league_path: "{{ college_teams["LSU"]['league_path'] }}"
          conference_id: "{{ college_teams["LSU"]['conference_id'] | string}}"
          is_singular: true
      - service: teamtracker.call_api
        target:
          entity_id: "{{ team_tracker }}"
        data:
          sport_path: "{{ sport_path }}"
          team_id: "{{ query_team }}"
          league_path: "{{ league_path }}"
          conference_id: "{{ conference_id }}"
mode: single
